name: Build and push docker image to ACR

on:
  workflow_call:
    inputs:
      azure-container-registry:
        required: true
        type: string
      project-name:
        required: true
        type: string
      build-version:
        required: true
        type: string
      dockerfile-path:
        required: true
        type: string
      docker-working-directory:
        type: string
    secrets:
      azure-container-registry-username:
        required: true
      azure-container-registry-password:
        required: true
    outputs:
      docker-image-url: 
        description: "The URL of the pushed image in ACR"
        value: ${{ jobs.build.outputs.docker-image-url }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_URL: '${{ inputs.azure-container-registry }}.azurecr.io/${{ inputs.project-name }}:${{ inputs.build-version }}'
    outputs:
      docker-image-url: ${{ env.DOCKER_IMAGE_URL }}
    steps:
    - uses: actions/checkout@main
    
    # Connect to Azure Container Registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ inputs.azure-container-registry }}.azurecr.io
        username: ${{ secrets.azure-container-registry-username }} 
        password: ${{ secrets.azure-container-registry-password }}
    
    # Container build and push to a Azure Container Registry (ACR)
    - run: |
        docker build . -f ${{ inputs.dockerfile-path }} -t ${{ env.DOCKER_IMAGE_URL }}
        docker push ${{ env.DOCKER_IMAGE_URL }}
      working-directory: ${{ inputs.docker-working-directory }}
  tag-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: |
          git tag -a ${{ inputs.build-version }}
          git push origin ${{ inputs.build-version }}
