name: Release
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: tsvgeorgieva/telerik-devops/.github/workflows/test.yml@main
  sast:
    uses: tsvgeorgieva/telerik-devops/.github/workflows/sast.yml@main
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      github_token: ${{ secrets.GITHUB_TOKEN }}


