name: Release
on:
  push:
    branches: [ main ]

env:
  BUILD_VERSION: ''
  AZURE_CONTAINER_REGISTRY: 'tsvetinaRegistry'
  PROJECT_NAME: 'library-app'
  RESOURCE_GROUP: 'telerik-devops'
  CLUSTER_NAME: 'telerik-devops-aks'
  CHART_PATH: './charts/library-app'

jobs:
  semver:
    uses: tsvgeorgieva/telerik-devops/.github/workflows/semver.yml@main
    with:
      version-format: "${major}.${minor}.${patch}.${increment}"

  test:
    uses: tsvgeorgieva/telerik-devops/.github/workflows/test.yml@main

  build:
    uses: tsvgeorgieva/telerik-devops/.github/workflows/docker-image.yml@main
    with:
      dockerfile-path: 'Library.WebAPI/Dockerfile'
      docker-working-directory: 'src/Library'
      azure-container-registry: ${{ env.AZURE_CONTAINER_REGISTRY }}
      project-name: ${{ env.PROJECT_NAME }}
      build-version: ${{ jobs.semver.outputs.build-version }}
    secrets:
      azure-container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
      azure-container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      
  deploy:
    uses: tsvgeorgieva/telerik-devops/.github/workflows/deploy.yml@main
    with:
      azure-resource-group: ${{ env.RESOURCE_GROUP }}
      aks-cluster-name: ${{ env.CLUSTER_NAME }}
      helm-chart-path: ${{ env.CHART_PATH }}
      build-version: ${{ jobs.semver.outputs.build-version }}
      docker-image-url: ${{ jobs.build.outputs.docker-image-url }}
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
